name    'boundary-boundary'
version '3.0.3'
source 'https://github.com/boundary/boundary_puppet'
author 'boundary'
license 'Apache 2.0'
summary 'Boundary meter module and event report handler'
description 'A module to install Boundary meters and event report handler.'
project_page 'https://github.com/boundary/boundary_puppet'
