name    'puppetlabs-boundary'
version '0.0.7'
source 'UNKNOWN'
author 'puppetlabs'
license 'Apache 2.0'
summary 'Boundary meter module'
description 'A module to install Boundary metrics meters.'
project_page 'https://github.com/puppetlabs/puppetlabs-boundary'
